version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: aegis-postgres
    environment:
      POSTGRES_USER: aegis_admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: aegis_db
    ports:
      - "5432:5432"
    volumes:
      - aegis_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  aegis_pg_data:
