[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CLERK_SIGN_IN_URL,NEXT_PUBLIC_CLERK_SIGN_UP_URL,NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,NEXT_PUBLIC_STRIPE_PRICE_DEVELOPER_MONTHLY,NEXT_PUBLIC_STRIPE_PRICE_GROWTH_MONTHLY,NEXT_PUBLIC_STRIPE_PRICE_GROWTH_YEARLY,NEXT_PUBLIC_STRIPE_PRICE_ENTERPRISE_MONTHLY,NEXT_PUBLIC_STRIPE_PRICE_ENTERPRISE_YEARLY,NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
